STATIONS = [

    # 🔴 RED LINE (Miyapur ↔ LB Nagar)
    "Miyapur",
    "JNTU College",
    "KPHB Colony",
    "Kukatpally",
    "Balanagar",
    "Moosapet",
    "Bharat Nagar",
    "Erragadda",
    "ESI Hospital",
    "Ameerpet",
    "Punjagutta",
    "Irrum Manzil",
    "Khairatabad",
    "Lakdi-ka-pul",
    "Assembly",
    "Nampally",
    "Gandhi Bhavan",
    "Osmania Medical College",
    "MG Bus Station",
    "Malakpet",
    "New Market",
    "Musarambagh",
    "Dilsukhnagar",
    "Chaitanyapuri",
    "Victoria Memorial",
    "LB Nagar",

    # 🔵 BLUE LINE (Raidurg ↔ Nagole)
    "Raidurg",
    "HITEC City",
    "Durgam Cheruvu",
    "Madhapur",
    "Peddamma Gudi",
    "Jubilee Hills Check Post",
    "Road No 5 Jubilee Hills",
    "Yusufguda",
    "Madhura Nagar",
    "Ameerpet",
    "Begumpet",
    "Prakash Nagar",
    "Rasoolpura",
    "Paradise",
    "Secunderabad East",
    "Mettuguda",
    "Tarnaka",
    "Habsiguda",
    "NGRI",
    "Stadium",
    "Uppal",
    "Nagole",

    # 🟢 GREEN LINE (JBS ↔ MGBS)
    "JBS Parade Ground",
    "Secunderabad West",
    "Gandhi Hospital",
    "Musheerabad",
    "RTC Cross Road",
    "Chikkadpally",
    "Narayanguda",
    "Sultan Bazaar",
    "MG Bus Station"
]
